//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class authorization_history
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int authorization_datetime_int { get; set; }
        public string ip_address { get; set; }
    
        public virtual users users { get; set; }
    }
}
