//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class black_list
    {
        public int id { get; set; }
        public int user_id_from { get; set; }
        public int user_id_blocked { get; set; }
        public int block_datetime_int { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
