//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class files_to_articles
    {
        public int id { get; set; }
        public int file_id { get; set; }
        public int article_id { get; set; }
    
        public virtual articles articles { get; set; }
        public virtual files files { get; set; }
    }
}
