//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class files_or_articles_to_collections
    {
        public int id { get; set; }
        public int object_id { get; set; }
        public int collection_id { get; set; }
    
        public virtual collections collections { get; set; }
        public virtual objects objects { get; set; }
    }
}
