//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public messages()
        {
            this.objects_with_name_to_messages = new HashSet<objects_with_name_to_messages>();
        }
    
        public int id { get; set; }
        public int user_id_from { get; set; }
        public int dialog_id { get; set; }
        public int creation_datetime_int { get; set; }
        public string text { get; set; }
        public int attached_record_id { get; set; }
    
        public virtual dialogs dialogs { get; set; }
        public virtual records records { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<objects_with_name_to_messages> objects_with_name_to_messages { get; set; }
    }
}
