//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities_Database_SocialNetwork : DbContext
    {
        public Entities_Database_SocialNetwork()
            : base("name=Entities_Database_SocialNetwork")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<articles> articles { get; set; }
        public virtual DbSet<authorization_history> authorization_history { get; set; }
        public virtual DbSet<bans> bans { get; set; }
        public virtual DbSet<black_list> black_list { get; set; }
        public virtual DbSet<collections> collections { get; set; }
        public virtual DbSet<commentaries> commentaries { get; set; }
        public virtual DbSet<commentaries_to_objects_with_commentaries> commentaries_to_objects_with_commentaries { get; set; }
        public virtual DbSet<dialogs> dialogs { get; set; }
        public virtual DbSet<files> files { get; set; }
        public virtual DbSet<files_or_articles_to_collections> files_or_articles_to_collections { get; set; }
        public virtual DbSet<files_to_articles> files_to_articles { get; set; }
        public virtual DbSet<friends_and_subscriptions> friends_and_subscriptions { get; set; }
        public virtual DbSet<messages> messages { get; set; }
        public virtual DbSet<object_types> object_types { get; set; }
        public virtual DbSet<objects> objects { get; set; }
        public virtual DbSet<objects_with_name_to_commentaries> objects_with_name_to_commentaries { get; set; }
        public virtual DbSet<objects_with_name_to_messages> objects_with_name_to_messages { get; set; }
        public virtual DbSet<objects_with_name_to_records> objects_with_name_to_records { get; set; }
        public virtual DbSet<objects_with_name_to_showcases> objects_with_name_to_showcases { get; set; }
        public virtual DbSet<privacy_settings> privacy_settings { get; set; }
        public virtual DbSet<privacy_settings_to_users> privacy_settings_to_users { get; set; }
        public virtual DbSet<ratings_to_objects_with_rating> ratings_to_objects_with_rating { get; set; }
        public virtual DbSet<records> records { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<users_to_dialogs> users_to_dialogs { get; set; }
    
        public virtual int isObjectAFileOrAnArticle(Nullable<int> object_type_id)
        {
            var object_type_idParameter = object_type_id.HasValue ?
                new ObjectParameter("object_type_id", object_type_id) :
                new ObjectParameter("object_type_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("isObjectAFileOrAnArticle", object_type_idParameter);
        }
    
        public virtual int isObjectAnObjectWithCommentary(Nullable<int> object_type_id)
        {
            var object_type_idParameter = object_type_id.HasValue ?
                new ObjectParameter("object_type_id", object_type_id) :
                new ObjectParameter("object_type_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("isObjectAnObjectWithCommentary", object_type_idParameter);
        }
    
        public virtual int isObjectAnObjectWithName(Nullable<int> object_type_id)
        {
            var object_type_idParameter = object_type_id.HasValue ?
                new ObjectParameter("object_type_id", object_type_id) :
                new ObjectParameter("object_type_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("isObjectAnObjectWithName", object_type_idParameter);
        }
    
        public virtual int isObjectAnObjectWithRating(Nullable<int> object_type_id)
        {
            var object_type_idParameter = object_type_id.HasValue ?
                new ObjectParameter("object_type_id", object_type_id) :
                new ObjectParameter("object_type_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("isObjectAnObjectWithRating", object_type_idParameter);
        }
    }
}
