//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class objects_with_name_to_records
    {
        public int id { get; set; }
        public int object_id { get; set; }
        public int record_id { get; set; }
    
        public virtual objects objects { get; set; }
        public virtual records records { get; set; }
    }
}
