//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class records
    {    
        public int id { get; set; }
        public int object_id { get; set; }
        public int user_id_to { get; set; }
        public string text { get; set; }
        public int attached_record_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<records> records1 { get; set; }
        public virtual records records2 { get; set; }
        public virtual users users { get; set; }
    }
}
