//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_to_dialogs
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int dialog_id { get; set; }
        public Nullable<byte> is_admin_of_the_dialog { get; set; }
    
        public virtual dialogs dialogs { get; set; }
        public virtual users users { get; set; }
    }
}
